# Generated by Django 2.2.3 on 2019-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20190714_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=120, unique=True, verbose_name='Email'),
        ),
    ]
