# Generated by Django 2.2.3 on 2019-07-14 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_board', models.CharField(max_length=120, verbose_name='Mother Board')),
                ('cpu', models.CharField(max_length=120, verbose_name='CPU')),
                ('ram_memory', models.CharField(help_text='if have more than one ram must be divide by a comma', max_length=120, verbose_name='RAM Memory')),
                ('video_card', models.CharField(blank=True, max_length=120, verbose_name='Video Card')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_user', to=settings.AUTH_USER_MODEL, verbose_name='Belong to user')),
            ],
        ),
    ]
